Repository Borewit/rate-limit-threshold, pull requests merged in 2024-08, with the labels that each got.

#58 Switch from ESLint to Biome linter
  biome.jsonc
  package.json
  test/test-rate-limiter.ts
  yarn.lock
Labels: DevOps

#57 Update README
  README.md
Labels: documentation

#66 Update ESMAScript to 2020
  README.md
  lib/index.ts
  tsconfig.json
Labels: improvement

#69 Update to yarn Berry
  .github/workflows/nodejs-ci.yml
  .gitignore
  .yarnrc.yml
  package.json
  yarn.lock
Labels: DevOps

#70 Fix milliseconds -> seconds in documentation
  README.md
  lib/rate-limit-threshold.ts
Labels: documentation
